// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TesteConversaoFahrenheitCelcius {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testeconversor() {
    driver.get("http://localhost:8080/ConversorTemperatura/");
    driver.manage().window().setSize(new Dimension(974, 1032));
    
    WebElement selecionaElemento = driver.findElement(By.name("opcoes1"));
    Select select1 = new Select(selecionaElemento);
    select1.selectByVisibleText("Fahrenheit");
    
    WebElement selecionaOutroElemento = driver.findElement(By.name("opcoes2"));
    Select select2 = new Select(selecionaOutroElemento);
    select2.selectByVisibleText("Celsius");

    driver.findElement(By.name("grau")).click();
    driver.findElement(By.name("grau")).sendKeys("212");
    driver.findElement(By.name("converter")).click();
    driver.findElement(By.cssSelector("h2:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("h2:nth-child(2)")).getText(), is("O resultado foi: 100"));
  }
}
